"""Streamlit UI for Prophet Labs government console."""
from __future__ import annotations

import pandas as pd
import streamlit as st

from prophet_labs.config.settings import load_categories, load_thresholds
from prophet_labs.tagging.engine import TaggingEngine
from prophet_labs.utils.logging import get_logger

LOGGER = get_logger(__name__)


def render_dashboard():
    st.set_page_config(page_title="Prophet Labs", layout="wide")
    st.title("Prophet Labs — Government Analytics Console")
    st.caption("Powered by NeuralProphet")

    categories = load_categories()
    thresholds = load_thresholds()
    engine = TaggingEngine(thresholds=thresholds)

    st.sidebar.header("Controls")
    selected_category = st.sidebar.selectbox("Category", list(categories.keys()))
    st.sidebar.write("Refresh data and retrain models from the scheduler or CLI.")

    st.subheader(f"{selected_category} Metrics")
    example_rows = [
        {
            "metric_id": metric_id,
            "metric_name": metric_id.replace("_", " ").title(),
            "category": selected_category,
            "jurisdiction": "AU",
            "ds": "2024-03-31",
            "value": 100.0,
            "unit": thresholds.get(metric_id, {}).get("unit", "units"),
            "source_name": "mock",
            "source_url": "https://data.gov.au/",
            "metadata": {"frequency": "quarterly"},
        }
        for metric_id in categories[selected_category]["metrics"]
    ]
    df = pd.DataFrame(example_rows)
    tagged = engine.tag_dataframe(df, value_col="value")
    st.dataframe(tagged[["metric_name", "category", "value", "unit", "status", "rationale"]])

    st.subheader("Forecast preview")
    st.write("Forecasts are generated by NeuralProphet and cached to disk.")


if __name__ == "__main__":
    render_dashboard()
