feeds:
  - id: "abc_politics"
    type: "surface_web"
    url: "https://www.abc.net.au/news/feed/2942460/rss.xml"
    category: "politics"
    jurisdiction: "AU"
    enabled: true
  - id: "smh_politics"
    type: "surface_web"
    url: "https://www.smh.com.au/rss/politics/federal.xml"
    category: "politics"
    jurisdiction: "AU"
    enabled: true
  - id: "rba_statements"
    type: "surface_web"
    url: "https://www.rba.gov.au/rss/rss.xml"
    category: "economy"
    jurisdiction: "AU"
    enabled: true
  - id: "bom_climate_updates"
    type: "surface_web"
    url: "https://www.bom.gov.au/rss/warnings_rss.xml"
    category: "energy_environment"
    jurisdiction: "AU"
    enabled: true
  - id: "energy_open_nem"
    type: "aggregator"
    url: "https://api.opennem.org.au/feed"
    category: "energy_environment"
    jurisdiction: "AU"
    enabled: true
  - id: "aspi_defence"
    type: "surface_web"
    url: "https://www.aspi.org.au/rss.xml"
    category: "defence_security"
    jurisdiction: "GLOBAL"
    enabled: true
  - id: "health_aihw_news"
    type: "surface_web"
    url: "https://www.aihw.gov.au/rss/news.xml"
    category: "health"
    jurisdiction: "AU"
    enabled: true
  - id: "justice_bocsar"
    type: "surface_web"
    url: "https://www.bocsar.nsw.gov.au/Pages/bocsar_rss.xml"
    category: "crime"
    jurisdiction: "NSW"
    enabled: true
  - id: "osint_darkweb_politics"
    type: "darkweb_osint"
    url: "https://osint-gateway.internal/api/v1/feeds/darkweb_politics_rss"
    category: "politics"
    jurisdiction: "GLOBAL"
    enabled: false
  - id: "osint_darkweb_economic"
    type: "darkweb_osint"
    url: "https://osint-gateway.internal/api/v1/feeds/darkweb_economic_intel"
    category: "economy"
    jurisdiction: "GLOBAL"
    enabled: false
  - id: "osint_darkweb_security"
    type: "darkweb_osint"
    url: "https://osint-gateway.internal/api/v1/feeds/darkweb_security_intel"
    category: "defence_security"
    jurisdiction: "GLOBAL"
    enabled: false
  - id: "osint_gateway_torrent_dht_signals"
    type: "darkweb_osint"
    url: "https://osint-gateway.internal/api/v1/feeds/torrent_dht_signals"
    category: "security_threats"
    jurisdiction: "GLOBAL"
    enabled: false
    notes: "Uses vetted OSINT gateway; no direct DHT/Tor access in-platform."
  - id: "aggregator_social_news"
    type: "aggregator"
    url: "https://secure-aggregator.internal/api/v1/feeds/social_news.json"
    category: "social"
    jurisdiction: "AU"
    enabled: true
    notes: "JSON aggregator feed delivered via internal gateway."
